api_platform:
    title: 'BileMo Customer API'
    description: 'BileMo Products reader and Customer Users management'
    version: '1.0.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld: [ 'application/ld+json' ]
        jsonhal: [ 'application/hal+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        pagination_client_items_per_page: true
        pagination_items_per_page: 10
